[package]
name = "util"
version = "0.1.0"
authors = ["David <david.bauske@googlemail.com>"]

[dependencies]
serde = "1.0.29"
serde_derive = "1.0.29"
bincode = "1.0.0"
tempdir = "0.3.6"
lazy_static = "1.0.0"
byteorder = "1.2.1"
chrono = "0.4.0"